-- Insert shared global market personas under the stable system-owned user.
-- Safe to re-run: metadata updates in place, operational avatar/readiness fields stay intact.

INSERT INTO public.users (id, email, name)
VALUES (
    '00000000-0000-0000-0000-000000000001',
    'persona-system@local.ai-influencer.invalid',
    'Persona System'
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.personas (
    id,
    user_id,
    name,
    description,
    voice_profile,
    platforms,
    is_active,
    persona_id,
    display_name,
    language,
    tts_voice,
    avatar_source_type,
    avatar_prompt,
    status,
    video_count,
    tone_default,
    market_default
)
VALUES
    (
        '77111111-1111-4111-8111-111111111111',
        '00000000-0000-0000-0000-000000000001',
        'Alex Rivera',
        'US English reviewer for North American app and lifestyle campaigns.',
        'Confident and polished',
        ARRAY['tiktok', 'instagram', 'youtube'],
        TRUE,
        'global-us-alex',
        'Alex Rivera',
        'English (US)',
        'en-US-Standard-F',
        'fal_ai',
        'Photorealistic studio headshot of Alex Rivera, globally appealing U.S. tech and lifestyle creator, confident expression, smart casual wardrobe, direct gaze, clean soft lighting, neutral backdrop, cinematic detail.',
        'draft',
        0,
        'confident',
        'united_states'
    ),
    (
        '77222222-2222-4222-8222-222222222222',
        '00000000-0000-0000-0000-000000000001',
        'Wei Chen',
        'Mandarin reviewer for China-focused consumer app and lifestyle campaigns.',
        'Measured and modern',
        ARRAY['tiktok', 'instagram', 'youtube'],
        TRUE,
        'global-cn-wei',
        'Wei Chen',
        'Mandarin',
        'cmn-CN-Standard-B',
        'fal_ai',
        'Photorealistic studio headshot of Wei Chen, Mandarin-speaking creator for China market, polished modern wardrobe, calm confident expression, direct gaze, soft editorial lighting, neutral backdrop, cinematic detail.',
        'draft',
        0,
        'measured',
        'china'
    ),
    (
        '77333333-3333-4333-8333-333333333333',
        '00000000-0000-0000-0000-000000000001',
        'Natasha Volkov',
        'Russian reviewer for Eastern Europe-focused app and travel campaigns.',
        'Direct and composed',
        ARRAY['tiktok', 'instagram', 'youtube'],
        TRUE,
        'global-ru-natasha',
        'Natasha Volkov',
        'Russian',
        'ru-RU-Standard-C',
        'fal_ai',
        'Photorealistic studio headshot of Natasha Volkov, Russian-speaking lifestyle reviewer, poised confident expression, contemporary city style, direct gaze, soft studio lighting, neutral backdrop, cinematic detail.',
        'draft',
        0,
        'direct',
        'russia'
    ),
    (
        '77444444-4444-4444-8444-444444444444',
        '00000000-0000-0000-0000-000000000001',
        'Arjun Sharma',
        'Indian English reviewer for India-focused mobile app and lifestyle campaigns.',
        'Upbeat and clear',
        ARRAY['tiktok', 'instagram', 'youtube'],
        TRUE,
        'global-in-arjun',
        'Arjun Sharma',
        'Indian English',
        'en-IN-Standard-D',
        'fal_ai',
        'Photorealistic studio headshot of Arjun Sharma, Indian English creator for India market, upbeat confident expression, modern casual blazer, direct gaze, soft studio lighting, neutral backdrop, cinematic detail.',
        'draft',
        0,
        'upbeat',
        'india'
    ),
    (
        '77555555-5555-4555-8555-555555555555',
        '00000000-0000-0000-0000-000000000001',
        'Valeria Cruz',
        'Mexican Spanish reviewer for Mexico-focused mobile app campaigns.',
        'Warm and persuasive',
        ARRAY['tiktok', 'instagram', 'youtube'],
        TRUE,
        'global-mx-valeria',
        'Valeria Cruz',
        'Mexican Spanish',
        'es-US-Standard-B',
        'fal_ai',
        'Photorealistic studio headshot of Valeria Cruz, Mexican Spanish creator for Mexico market, warm confident expression, stylish casual wardrobe, direct gaze, soft studio lighting, neutral backdrop, cinematic detail.',
        'draft',
        0,
        'warm',
        'mexico'
    )
ON CONFLICT (user_id, persona_id) DO UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    voice_profile = EXCLUDED.voice_profile,
    platforms = EXCLUDED.platforms,
    is_active = EXCLUDED.is_active,
    display_name = EXCLUDED.display_name,
    language = EXCLUDED.language,
    tts_voice = EXCLUDED.tts_voice,
    avatar_source_type = EXCLUDED.avatar_source_type,
    avatar_prompt = EXCLUDED.avatar_prompt,
    tone_default = EXCLUDED.tone_default,
    market_default = EXCLUDED.market_default,
    updated_at = NOW();
