import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        // AI-Influencer / Professional Steel design system
        brand: {
          primary:        "#a03929",
          "primary-dim":  "#902d1f",
          "primary-container": "#fd7d68",
          "primary-fixed": "#fd7d68",
          "primary-fixed-dim": "#ec715d",
          "on-primary":   "#ffefed",
          "on-primary-container": "#520300",
          secondary:      "#705900",
          "secondary-dim": "#624d00",
          "secondary-container": "#fdd34d",
          "secondary-fixed": "#fdd34d",
          "secondary-fixed-dim": "#eec540",
          "on-secondary": "#fff2d4",
          "on-secondary-container": "#5c4900",
          "on-secondary-fixed": "#463600",
          "on-secondary-fixed-variant": "#675200",
          tertiary:       "#00684f",
          "tertiary-dim": "#005b45",
          "tertiary-container": "#98ffd9",
          "tertiary-fixed": "#98ffd9",
          "tertiary-fixed-dim": "#89f0cb",
          "on-tertiary":  "#c6ffe7",
          "on-tertiary-container": "#00634b",
          "on-tertiary-fixed": "#004f3b",
          "on-tertiary-fixed-variant": "#006e54",
          surface:        "#f8f6f1",
          "surface-dim":  "#d5d5ce",
          "surface-bright": "#f8f6f1",
          "surface-container-lowest": "#ffffff",
          "surface-container-low": "#f2f1eb",
          "surface-container": "#eae8e3",
          "surface-container-high": "#e4e2dd",
          "surface-container-highest": "#deddd7",
          "surface-variant": "#deddd7",
          "surface-tint":  "#a03929",
          "on-surface":   "#2e2f2c",
          "on-surface-variant": "#5c5c58",
          "on-background": "#2e2f2c",
          outline:        "#777773",
          "outline-variant": "#aeada9",
          "inverse-surface": "#0e0e0c",
          "inverse-primary": "#fd7d68",
          "inverse-on-surface": "#9e9d99",
          error:          "#b41340",
          "error-dim":    "#a70138",
          "error-container": "#f74b6d",
          "on-error":     "#ffefef",
          "on-error-container": "#510017",
        },
        // Keep original primary for non-dashboard pages
        primary: {
          50: "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          300: "#7dd3fc",
          400: "#38bdf8",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
          800: "#075985",
          900: "#0c4a6e",
        },
      },
      fontFamily: {
        sans: ['Lexend', 'system-ui', '-apple-system', 'Inter', 'sans-serif'],
        headline: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        body: ['Lexend', 'system-ui', 'sans-serif'],
        label: ['Lexend', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.375rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      animation: {
        "fade-in": "fadeIn 300ms ease-out",
        "slide-up": "slideUp 300ms cubic-bezier(0.4, 0.0, 0.2, 1)",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
      transitionTimingFunction: {
        apple: "cubic-bezier(0.4, 0.0, 0.2, 1)",
      },
      backdropBlur: {
        xs: "2px",
      },
      boxShadow: {
        brand: "0 20px 40px rgba(0,0,0,0.1)",
        "brand-md": "0 8px 24px rgba(0,0,0,0.12)",
        "brand-sm": "0 2px 8px rgba(0,0,0,0.08)",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};

export default config;
