'use client';

import { useEffect, useMemo, useState } from 'react';
import type { Dispatch, SetStateAction } from 'react';
import type { PersonaPlanCardViewModel, PlanCardStatus } from '@/types/video-planning';

interface CreateVideoReviewStepProps {
  planCards: PersonaPlanCardViewModel[];
  onCardsChange: Dispatch<SetStateAction<PersonaPlanCardViewModel[]>>;
  onContinue: () => void;
  onBack: () => void;
}

const STATUS_META: Record<PlanCardStatus, { label: string; className: string }> = {
  loading: { label: 'Loading', className: 'cv-badge cv-badge--loading' },
  demo: { label: 'Draft plan', className: 'cv-badge cv-badge--demo' },
  ready: { label: 'Ready', className: 'cv-badge cv-badge--ready' },
  approved: { label: 'Approved', className: 'cv-badge cv-badge--approved' },
  rejected: { label: 'Rejected', className: 'cv-badge cv-badge--rejected' },
  pending_backend: { label: 'Pending backend', className: 'cv-badge cv-badge--pending' },
};

export function CreateVideoReviewStep({
  planCards,
  onCardsChange,
  onContinue,
  onBack,
}: CreateVideoReviewStepProps) {
  const [isEditingContract, setIsEditingContract] = useState(false);
  const [globalScript, setGlobalScript] = useState('');
  const [globalScenes, setGlobalScenes] = useState('');

  const approvedCount = planCards.filter((card) => card.status === 'approved').length;
  const canContinue = approvedCount > 0;

  const parseScenes = (input: string) => {
    const rows = input
      .split('\n')
      .map((row) => row.trim())
      .filter(Boolean);

    return rows.map((row, idx) => {
      const [descPart, durationPart] = row.split('|').map((part) => part.trim());
      const duration = durationPart ? Number(durationPart.replace(/[^\d.]/g, '')) : NaN;
      return {
        index: idx + 1,
        description: descPart || `Scene ${idx + 1}`,
        durationSeconds: Number.isFinite(duration) ? duration : undefined,
      };
    });
  };

  const contractStatus: PlanCardStatus =
    approvedCount === planCards.length
      ? 'approved'
      : approvedCount === 0
        ? 'rejected'
        : 'ready';

  const contractStatusMeta = STATUS_META[contractStatus];

  useEffect(() => {
    if (planCards.length === 0) {
      return;
    }
    if (globalScript.trim() || globalScenes.trim()) {
      return;
    }

    const firstCard = planCards[0];
    setGlobalScript(firstCard?.scriptPreview || '');
    setGlobalScenes(
      (firstCard?.scenes || [])
        .map((scene) =>
          `${scene.description}${scene.durationSeconds !== undefined ? ` | ${scene.durationSeconds}` : ''}`,
        )
        .join('\n'),
    );
  }, [globalScenes, globalScript, planCards]);

  const applyContractToAll = () => {
    const parsedScenes = parseScenes(globalScenes);
    onCardsChange((cards) =>
      cards.map((card) => ({
        ...card,
        scriptPreview: globalScript.trim() ? globalScript : card.scriptPreview,
        scenes: parsedScenes.length > 0 ? parsedScenes : card.scenes,
      })),
    );
  };

  const setContractStatus = (status: Extract<PlanCardStatus, 'approved' | 'rejected'>) => {
    onCardsChange((cards) => cards.map((card) => ({ ...card, status })));
  };

  const timelineRows = useMemo(() => {
    const scenes = parseScenes(globalScenes);
    let currentSecond = 0;
    return scenes.map((scene) => {
      const duration = scene.durationSeconds ?? 0;
      const startSecond = currentSecond;
      const endSecond = duration > 0 ? currentSecond + duration : currentSecond;
      currentSecond = endSecond;
      return {
        index: scene.index,
        secondLabel: duration > 0 ? `${startSecond}s - ${endSecond}s` : `${startSecond}s`,
        description: scene.description,
      };
    });
  }, [globalScenes]);

  if (planCards.length === 0) {
    return (
      <div className="cv-empty-state">
        <p>No persona plans were generated. Go back and select at least one persona.</p>
        <button type="button" onClick={onBack} className="cv-back-btn">← Go back</button>
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      <div className="cv-step-header">
        <button type="button" onClick={onBack} className="cv-back-btn">← Back</button>
        <div>
          <h2 className="cv-step-heading">Review Plan</h2>
          <p className="cv-step-sub">
            Contract is auto-generated by AI after setup summary. You can review and adjust before render.
          </p>
        </div>
      </div>

      <section className="cv-section-card" style={{ marginBottom: 0 }}>
        <div className="cv-section-header" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10 }}>
          <h3 className="cv-section-title" style={{ margin: 0 }}>
            Contract Overview
            <span className="cv-section-badge cv-section-badge--optional">AI generated</span>
          </h3>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span className={contractStatusMeta.className}>{contractStatusMeta.label}</span>
            <button
              type="button"
              className="cv-action-btn cv-action-btn--reject"
              onClick={() => setContractStatus('rejected')}
            >
              Reject
            </button>
            <button
              type="button"
              className="cv-action-btn cv-action-btn--approve"
              onClick={() => setContractStatus('approved')}
            >
              Approve
            </button>
            <button
              type="button"
              className="cv-persona-action-btn"
              onClick={() => setIsEditingContract((v) => !v)}
            >
              {isEditingContract ? 'Done' : 'Edit'}
            </button>
          </div>
        </div>

        <div className="cv-section-content" style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          <div>
            <p className="cv-card-section-label" style={{ marginBottom: 6 }}>Script Contract</p>
            {isEditingContract ? (
              <textarea
                className="cv-input cv-textarea"
                rows={6}
                value={globalScript}
                onChange={(event) => setGlobalScript(event.target.value)}
                placeholder="AI will generate script contract here..."
              />
            ) : (
              <p className="cv-script-text cv-script-text--expanded">
                {globalScript.trim() || 'No contract script generated yet.'}
              </p>
            )}
          </div>

          <div>
            <p className="cv-card-section-label" style={{ marginBottom: 6 }}>Scene Timeline</p>
            {isEditingContract ? (
              <textarea
                className="cv-input cv-textarea"
                rows={6}
                value={globalScenes}
                onChange={(event) => setGlobalScenes(event.target.value)}
                placeholder={"One scene per line. Format: Scene text | 6\nExample: Hook about product value | 5"}
              />
            ) : timelineRows.length === 0 ? (
              <p className="cv-cta-disabled-reason">No scene timeline generated yet.</p>
            ) : (
              <ol className="cv-scene-list">
                {timelineRows.map((row) => (
                  <li key={`${row.index}-${row.secondLabel}`} className="cv-scene-item">
                    <span style={{ display: 'inline-flex', minWidth: 98, fontWeight: 700 }}>{row.secondLabel}</span>
                    <span>{row.description}</span>
                  </li>
                ))}
              </ol>
            )}
          </div>

          {isEditingContract && (
            <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
              <button type="button" className="btn-primary" onClick={applyContractToAll}>
                Apply edits to selected personas
              </button>
            </div>
          )}
        </div>
      </section>

      <section className="cv-section-card" style={{ marginBottom: 0 }}>
        <div className="cv-section-header" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <h3 className="cv-section-title" style={{ margin: 0 }}>
            Selected Personas
            <span className="cv-section-badge cv-section-badge--optional">{planCards.length} selected</span>
          </h3>
        </div>
        <div className="cv-section-content" style={{ display: 'grid', gap: 8 }}>
          {planCards.map((card) => (
            <div
              key={card.personaId}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 10,
                border: '1px solid rgb(174 173 169 / 0.2)',
                borderRadius: 12,
                padding: '8px 10px',
              }}
            >
              <PersonaAvatar name={card.personaName} avatarUrl={card.personaAvatarUrl} size={30} />
              <span className="cv-card-persona-name">{card.personaName}</span>
            </div>
          ))}
        </div>
      </section>

      <div className="cv-continue-bar">
        <div className="cv-cta-wrap">
          <button
            type="button"
            onClick={canContinue ? onContinue : undefined}
            disabled={!canContinue}
            className="btn-primary btn-wide"
          >
            Render Approved Videos →
          </button>
          {!canContinue && (
            <p className="cv-cta-disabled-reason">
              Approve contract to continue.
            </p>
          )}
        </div>
      </div>
    </div>
  );
}

function PersonaAvatar({ name, avatarUrl, size }: { name: string; avatarUrl?: string; size: number }) {
  if (avatarUrl) {
    return (
      <img
        src={avatarUrl}
        alt={name}
        className="cv-avatar"
        style={{ width: size, height: size }}
        loading="lazy"
        decoding="async"
      />
    );
  }

  return (
    <div
      className="cv-avatar-fallback"
      style={{ width: size, height: size, fontSize: size * 0.4 }}
    >
      {name.charAt(0).toUpperCase()}
    </div>
  );
}
